steps:
# Step 1: Build the application using Google Cloud Buildpacks
- name: 'gcr.io/buildpacks/builder'
  args: ['pack', 'build', 'gcr.io/my-sample-project1-424605/hello-world']
  dir: '.'

# Step 2: Deploy the built application to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'hello-world'
    - '--image'
    - 'gcr.io/my-sample-project1-424605/hello-world'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1-a'
    - '--allow-unauthenticated'
